# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: K8SCert"
kfutil store-types create K8SCert

Write-Host "Creating store type: K8SCluster"
kfutil store-types create K8SCluster

Write-Host "Creating store type: K8SJKS"
kfutil store-types create K8SJKS

Write-Host "Creating store type: K8SNS"
kfutil store-types create K8SNS

Write-Host "Creating store type: K8SPKCS12"
kfutil store-types create K8SPKCS12

Write-Host "Creating store type: K8SSecret"
kfutil store-types create K8SSecret

Write-Host "Creating store type: K8STLSSecr"
kfutil store-types create K8STLSSecr

