# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: K8SCert"
$Body = @'
{
  "Name": "K8SCert",
  "ShortName": "K8SCert",
  "Capability": "K8SCert",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Description": "This should be no value or \u0060kubeconfig\u0060",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Description": "The credentials to use to connect to the K8S cluster API. This needs to be in \u0060kubeconfig\u0060 format. Example: https://github.com/Keyfactor/k8s-orchestrator/tree/main/scripts/kubernetes#example-service-account-json",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": true
    },
    {
      "Name": "KubeSecretName",
      "DisplayName": "KubeSecretName",
      "Description": "The name of a specific CSR to inventory. Leave empty or set to \u0027*\u0027 to inventory ALL issued CSRs in the cluster.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Forbidden",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: K8SCluster"
$Body = @'
{
  "Name": "K8SCluster",
  "ShortName": "K8SCluster",
  "Capability": "K8SCluster",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "true",
      "Required": false,
      "Description": "Will default to \u0060true\u0060 if not set. If set to \u0060false\u0060 only the leaf cert will be deployed. Note: If the certificate in Keyfactor Command does not have a private key, it will be sent in DER format (leaf certificate only), and the chain cannot be included regardless of this setting."
    },
    {
      "Name": "SeparateChain",
      "DisplayName": "Separate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "false",
      "Required": false,
      "Description": "Will default to \u0060false\u0060 if not set. Set this to \u0060true\u0060 if you want to deploy certificate chain to the \u0060ca.crt\u0060 field for Opaque and tls secrets."
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Description": "This should be no value or \u0060kubeconfig\u0060",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Description": "The credentials to use to connect to the K8S cluster API. This needs to be in \u0060kubeconfig\u0060 format. Example: https://github.com/Keyfactor/k8s-orchestrator/tree/main/scripts/kubernetes#example-service-account-json",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: K8SJKS"
$Body = @'
{
  "Name": "K8SJKS",
  "ShortName": "K8SJKS",
  "Capability": "K8SJKS",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "KubeNamespace",
      "DisplayName": "KubeNamespace",
      "Description": "The K8S namespace to use to manage the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "default",
      "Required": false
    },
    {
      "Name": "KubeSecretName",
      "DisplayName": "KubeSecretName",
      "Description": "The name of the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "KubeSecretType",
      "DisplayName": "KubeSecretType",
      "Description": "DEPRECATED: This property is deprecated and will be removed in a future release. The secret type is now automatically derived from the store type. This defaults to and must be \u0060jks\u0060.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "jks",
      "Required": false
    },
    {
      "Name": "CertificateDataFieldName",
      "DisplayName": "CertificateDataFieldName",
      "Description": "The field name to use when looking for certificate data in the K8S secret.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "PasswordFieldName",
      "DisplayName": "PasswordFieldName",
      "Description": "The field name to use when looking for the JKS keystore password in the K8S secret. This is either the field name to look at on the same secret, or if \u0060PasswordIsK8SSecret\u0060 is set to \u0060true\u0060, the field name to look at on the secret specified in \u0060StorePasswordPath\u0060.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "password",
      "Required": false
    },
    {
      "Name": "PasswordIsK8SSecret",
      "DisplayName": "PasswordIsK8SSecret",
      "Description": "Indicates whether the password to the JKS keystore is stored in a separate K8S secret.",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "true",
      "Required": false,
      "Description": "Will default to \u0060true\u0060 if not set. If set to \u0060false\u0060 only the leaf cert will be deployed. Note: If the certificate in Keyfactor Command does not have a private key, it will be sent in DER format (leaf certificate only), and the chain cannot be included regardless of this setting."
    },
    {
      "Name": "StorePasswordPath",
      "DisplayName": "StorePasswordPath",
      "Description": "The path to the K8S secret object to use as the password to the JKS keystore. Example: \u0060\u003Cnamespace\u003E/\u003Csecret_name\u003E\u0060",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Description": "This should be no value or \u0060kubeconfig\u0060",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Description": "The credentials to use to connect to the K8S cluster API. This needs to be in \u0060kubeconfig\u0060 format. Example: https://github.com/Keyfactor/k8s-orchestrator/tree/main/scripts/kubernetes#example-service-account-json",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": true,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: K8SNS"
$Body = @'
{
  "Name": "K8SNS",
  "ShortName": "K8SNS",
  "Capability": "K8SNS",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "KubeNamespace",
      "DisplayName": "Kube Namespace",
      "Description": "The K8S namespace to use to manage the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "default",
      "Required": false
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "true",
      "Required": false,
      "Description": "Will default to \u0060true\u0060 if not set. If set to \u0060false\u0060 only the leaf cert will be deployed. Note: If the certificate in Keyfactor Command does not have a private key, it will be sent in DER format (leaf certificate only), and the chain cannot be included regardless of this setting."
    },
    {
      "Name": "SeparateChain",
      "DisplayName": "Separate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "false",
      "Required": false,
      "Description": "Will default to \u0060false\u0060 if not set. Set this to \u0060true\u0060 if you want to deploy certificate chain to the \u0060ca.crt\u0060 field for Opaque and tls secrets."
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Description": "This should be no value or \u0060kubeconfig\u0060",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Description": "The credentials to use to connect to the K8S cluster API. This needs to be in \u0060kubeconfig\u0060 format. Example: https://github.com/Keyfactor/k8s-orchestrator/tree/main/scripts/kubernetes#example-service-account-json",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: K8SPKCS12"
$Body = @'
{
  "Name": "K8SPKCS12",
  "ShortName": "K8SPKCS12",
  "Capability": "K8SPKCS12",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "true",
      "Required": false,
      "Description": "Will default to \u0060true\u0060 if not set. If set to \u0060false\u0060 only the leaf cert will be deployed. Note: If the certificate in Keyfactor Command does not have a private key, it will be sent in DER format (leaf certificate only), and the chain cannot be included regardless of this setting."
    },
    {
      "Name": "CertificateDataFieldName",
      "DisplayName": "CertificateDataFieldName",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": ".p12",
      "Required": true
    },
    {
      "Name": "PasswordFieldName",
      "DisplayName": "Password Field Name",
      "Description": "The field name to use when looking for the PKCS12 keystore password in the K8S secret. This is either the field name to look at on the same secret, or if \u0060PasswordIsK8SSecret\u0060 is set to \u0060true\u0060, the field name to look at on the secret specified in \u0060StorePasswordPath\u0060.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "password",
      "Required": false
    },
    {
      "Name": "PasswordIsK8SSecret",
      "DisplayName": "Password Is K8S Secret",
      "Description": "Indicates whether the password to the PKCS12 keystore is stored in a separate K8S secret object.",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "KubeNamespace",
      "DisplayName": "Kube Namespace",
      "Description": "The K8S namespace to use to manage the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "default",
      "Required": false
    },
    {
      "Name": "KubeSecretName",
      "DisplayName": "Kube Secret Name",
      "Description": "The name of the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Description": "This should be no value or \u0060kubeconfig\u0060",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Description": "The credentials to use to connect to the K8S cluster API. This needs to be in \u0060kubeconfig\u0060 format. Example: https://github.com/Keyfactor/k8s-orchestrator/tree/main/scripts/kubernetes#example-service-account-json",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "KubeSecretType",
      "DisplayName": "Kube Secret Type",
      "Description": "DEPRECATED: This property is deprecated and will be removed in a future release. The secret type is now automatically derived from the store type. This defaults to and must be \u0060pkcs12\u0060.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "pkcs12",
      "Required": false
    },
    {
      "Name": "StorePasswordPath",
      "DisplayName": "StorePasswordPath",
      "Description": "The path to the K8S secret object to use as the password to the PFX/PKCS12 data. Example: \u0060\u003Cnamespace\u003E/\u003Csecret_name\u003E\u0060",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": true,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: K8SSecret"
$Body = @'
{
  "Name": "K8SSecret",
  "ShortName": "K8SSecret",
  "Capability": "K8SSecret",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "KubeNamespace",
      "DisplayName": "KubeNamespace",
      "Description": "The K8S namespace to use to manage the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "KubeSecretName",
      "DisplayName": "KubeSecretName",
      "Description": "The name of the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "KubeSecretType",
      "DisplayName": "KubeSecretType",
      "Description": "DEPRECATED: This property is deprecated and will be removed in a future release. The secret type is now automatically derived from the store type. This defaults to and must be \u0060secret\u0060.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "secret",
      "Required": false
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "true",
      "Required": false,
      "Description": "Will default to \u0060true\u0060 if not set. If set to \u0060false\u0060 only the leaf cert will be deployed. Note: If the certificate in Keyfactor Command does not have a private key, it will be sent in DER format (leaf certificate only), and the chain cannot be included regardless of this setting."
    },
    {
      "Name": "SeparateChain",
      "DisplayName": "Separate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "false",
      "Required": false,
      "Description": "Will default to \u0060false\u0060 if not set. Set this to \u0060true\u0060 if you want to deploy certificate chain to the \u0060ca.crt\u0060 field for Opaque and tls secrets."
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Description": "This should be no value or \u0060kubeconfig\u0060",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Description": "The credentials to use to connect to the K8S cluster API. This needs to be in \u0060kubeconfig\u0060 format. Example: https://github.com/Keyfactor/k8s-orchestrator/tree/main/scripts/kubernetes#example-service-account-json",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: K8STLSSecr"
$Body = @'
{
  "Name": "K8STLSSecr",
  "ShortName": "K8STLSSecr",
  "Capability": "K8STLSSecr",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "KubeNamespace",
      "DisplayName": "KubeNamespace",
      "Description": "The K8S namespace to use to manage the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "KubeSecretName",
      "DisplayName": "KubeSecretName",
      "Description": "The name of the K8S secret object.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "KubeSecretType",
      "DisplayName": "KubeSecretType",
      "Description": "DEPRECATED: This property is deprecated and will be removed in a future release. The secret type is now automatically derived from the store type. This defaults to and must be \u0060tls_secret\u0060.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "tls_secret",
      "Required": false
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "true",
      "Required": false,
      "Description": "Will default to \u0060true\u0060 if not set. If set to \u0060false\u0060 only the leaf cert will be deployed. Note: If the certificate in Keyfactor Command does not have a private key, it will be sent in DER format (leaf certificate only), and the chain cannot be included regardless of this setting."
    },
    {
      "Name": "SeparateChain",
      "DisplayName": "Separate Chain",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "false",
      "Required": false,
      "Description": "Will default to \u0060false\u0060 if not set. Set this to \u0060true\u0060 if you want to deploy certificate chain to the \u0060ca.crt\u0060 field for Opaque and tls secrets."
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Description": "This should be no value or \u0060kubeconfig\u0060",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Description": "The credentials to use to connect to the K8S cluster API. This needs to be in \u0060kubeconfig\u0060 format. Example: https://github.com/Keyfactor/k8s-orchestrator/tree/main/scripts/kubernetes#example-service-account-json",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": null,
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

