name: Auto Changelog
on:
  push:
    branches:
      - main
      - release*
      - pan_feedback
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autochangelog
        uses: rubenfiszel/autochangelog-action@v0.16.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}