name: "Dependency Submission"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependency-submission:
    name: Submit Dependencies to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Submit NuGet Dependencies
        uses: darenm/nuget-dependency-submission@v1
        with:
          solution: Keyfactor.Orchestrators.K8S.sln
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
