name: Run Kube Test Console Application

on: [push]
  
jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup build environment
        id: setup_env
        run: |
            $repoName = "${{ github.repository }}".Split("/")
            echo "Repo Name: $($repoName[-1])"
            echo "REPO_NAME=$($repoName[-1])" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
            $slnPath = (Get-ChildItem -Include *.sln -File -Recurse).fullname
            echo "Solution File Path: ${slnPath}"
            echo "SOLUTION_PATH=${slnPath}" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
            $creatingRelease = ("${{ inputs.release_url }}".Trim().Length -gt 0) -and ("${{ inputs.release_dir }}".Trim().Length -gt 0)
            echo "Flagged to create release: ${creatingRelease}"
            echo "CREATE_RELEASE=${creatingRelease}" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
            dotnet nuget add source https://nuget.pkg.github.com/Keyfactor/index.json -n github -u ${{ github.actor }} -p ${{ secrets.BUILD_PACKAGE_ACCESS }} --store-password-in-clear-text
            nuget restore $slnPath
        env:
          nuget_token: ${{ secrets.nuget_token }}
          
      - name: Build solution
        run: dotnet build

      - name: Run inventory tests
        run: dotnet run --project ./src/ConsoleApp/ConsoleApp.csproj
        env:
          KEYFACTOR_HOSTNAME: ${{ env.KEYFACTOR_HOSTNAME }}
          KEYFACTOR_DOMAIN: ${{ env.KEYFACTOR_DOMAIN }}
          KEYFACTOR_USERNAME: ${{ env.KEYFACTOR_USERNAME }}
          KEYFACTOR_PASSWORD: ${{ secrets.KEYFACTOR_PASSWORD }}
          TEST_KUBECONFIG: ${{ secrets.TEST_KUBECONFIG }}
          TEST_KUBE_NAMESPACE: ${{ env.TEST_KUBE_NAMESPACE }}
          TEST_MANUAL: false
          TEST_CERT_MGMT_TYPE: "inv"
          TEST_ORCH_OPERATION: "inv"
#      - name: Run management add tests
#        run:
#          - dotnet run --project ./src/ConsoleApp/ConsoleApp.csproj
#        env:
#          KEYFACTOR_HOSTNAME: ${{ env.KEYFACTOR_HOSTNAME }}
#          KEYFACTOR_DOMAIN: ${{ env.KEYFACTOR_DOMAIN }}
#          KEYFACTOR_USERNAME: ${{ env.KEYFACTOR_USERNAME }}
#          KEYFACTOR_PASSWORD: ${{ secrets.KEYFACTOR_PASSWORD }}
#          TEST_KUBECONFIG: ${{ secrets.TEST_KUBECONFIG }}
#          TEST_KUBE_NAMESPACE: ${{ env.TEST_KUBE_NAMESPACE }}
#          TEST_MANUAL: false
#          TEST_CERT_MGMT_TYPE: "add"
#          TEST_ORCH_OPERATION: "management"
#      - name: Run inventory tests post add
#        run:
#          - dotnet run --project ./src/ConsoleApp/ConsoleApp.csproj
#        env:
#          KEYFACTOR_HOSTNAME: ${{ env.KEYFACTOR_HOSTNAME }}
#          KEYFACTOR_DOMAIN: ${{ env.KEYFACTOR_DOMAIN }}
#          KEYFACTOR_USERNAME: ${{ env.KEYFACTOR_USERNAME }}
#          KEYFACTOR_PASSWORD: ${{ secrets.KEYFACTOR_PASSWORD }}
#          TEST_KUBECONFIG: ${{ secrets.TEST_KUBECONFIG }}
#          TEST_KUBE_NAMESPACE: ${{ env.TEST_KUBE_NAMESPACE }}
#          TEST_MANUAL: false
#          TEST_CERT_MGMT_TYPE: "inv"
#          TEST_ORCH_OPERATION: "inv"
#      - name: Run remove tests
#        run:
#          - dotnet run --project ./src/ConsoleApp/ConsoleApp.csproj
#        env:
#          KEYFACTOR_HOSTNAME: ${{ env.KEYFACTOR_HOSTNAME }}
#          KEYFACTOR_DOMAIN: ${{ env.KEYFACTOR_DOMAIN }}
#          KEYFACTOR_USERNAME: ${{ env.KEYFACTOR_USERNAME }}
#          KEYFACTOR_PASSWORD: ${{ secrets.KEYFACTOR_PASSWORD }}
#          TEST_KUBECONFIG: ${{ secrets.TEST_KUBECONFIG }}
#          TEST_KUBE_NAMESPACE: ${{ env.TEST_KUBE_NAMESPACE }}
#          TEST_MANUAL: false
#          TEST_CERT_MGMT_TYPE: "rem"
#          TEST_ORCH_OPERATION: "management"
#      - name: Run inventory tests post remove
#        run:
#          - dotnet run --project ./src/ConsoleApp/ConsoleApp.csproj
#        env:
#          KEYFACTOR_HOSTNAME: ${{ env.KEYFACTOR_HOSTNAME }}
#          KEYFACTOR_DOMAIN: ${{ env.KEYFACTOR_DOMAIN }}
#          KEYFACTOR_USERNAME: ${{ env.KEYFACTOR_USERNAME }}
#          KEYFACTOR_PASSWORD: ${{ secrets.KEYFACTOR_PASSWORD }}
#          TEST_KUBECONFIG: ${{ secrets.TEST_KUBECONFIG }}
#          TEST_KUBE_NAMESPACE: ${{ env.TEST_KUBE_NAMESPACE }}
#          TEST_MANUAL: false
#          TEST_CERT_MGMT_TYPE: "inv"
#          TEST_ORCH_OPERATION: "inv"