name: Run Kube Test Console Application

on: [push]

env:
  KEYFACTOR_PASSWORD: ${{ secrets.KEYFACTOR_PASSWORD }}
  TEST_KUBECONFIG: ${{ secrets.TEST_KUBECONFIG }}

jobs:
  get-manifest-properties:
    runs-on: windows-latest
    outputs:
      update_catalog: ${{ steps.read-json.outputs.prop }}
    steps:
      - uses: actions/checkout@v3
      - name: Read json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content integration-manifest.json | ConvertFrom-Json
          echo "::set-output name=prop::$(echo $json.update_catalog)"
  
  
  #  call-dotnet-build-and-release-workflow:
  #    needs: [call-create-github-release-workflow]
  #    uses: Keyfactor/actions/.github/workflows/dotnet-build-and-release.yml@main
  #    with:
  #      release_version: ${{ needs.call-create-github-release-workflow.outputs.release_version }}
  #      release_url: ${{ needs.call-create-github-release-workflow.outputs.release_url }}
  #      release_dir: kubernetes-orchestrator-extension\bin\Release\ 
  #    secrets: 
  #      token: ${{ secrets.PRIVATE_PACKAGE_ACCESS }}

  call-dotnet-build-and-test-workflow:
    #    needs: [ get-manifest-properties ]
    uses: spbsoluble/actions/.github/workflows/dotnet-build-and-test.yml@test_console
    with:
      release_dir: kubernetes-orchestrator-extension\bin\Release\
      test_working_dir: TestConsole
      test_sln_path: TestConsole\TestConsole.sln
      KEYFACTOR_HOSTNAME: ${{ env.KEYFACTOR_HOSTNAME }}
      KEYFACTOR_DOMAIN: ${{ env.KEYFACTOR_DOMAIN }}
    secrets:
      token: ${{ secrets.PRIVATE_PACKAGE_ACCESS }}
      KEYFACTOR_USERNAME: ${{ env.KEYFACTOR_USERNAME }}
      KEYFACTOR_PASSWORD: ${{ secrets.KEYFACTOR_PASSWORD }}
      TEST_PAM_MOCK_USERNAME: "kubeconfig"
      TEST_PAM_MOCK_PASSWORD: ${{ secrets.TEST_KUBECONFIG }}
      
      

#  call-generate-readme-workflow:
#    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
#    uses: Keyfactor/actions/.github/workflows/generate-readme.yml@main
#    secrets:
#      token: ${{ secrets.APPROVE_README_PUSH }}
#
#  call-update-catalog-workflow:
#    needs: get-manifest-properties
#    if: needs.get-manifest-properties.outputs.update_catalog == 'True' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
#    uses: Keyfactor/actions/.github/workflows/update-catalog.yml@main
#    secrets: 
#      token: ${{ secrets.SDK_SYNC_PAT }}
