#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: K8SCert"
kfutil store-types create K8SCert

echo "Creating store type: K8SCluster"
kfutil store-types create K8SCluster

echo "Creating store type: K8SJKS"
kfutil store-types create K8SJKS

echo "Creating store type: K8SNS"
kfutil store-types create K8SNS

echo "Creating store type: K8SPKCS12"
kfutil store-types create K8SPKCS12

echo "Creating store type: K8SSecret"
kfutil store-types create K8SSecret

echo "Creating store type: K8STLSSecr"
kfutil store-types create K8STLSSecr

